In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('site/src/data/table-indicateurs-open-data-dep-2023-06-30-17h59.csv')

C:\Users\willd\AppData\Roaming\Python\Python39\site-packages\IPython\core\interactiveshell.py:3194: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [5]:
df.dep = df.dep.apply(lambda x: f'{x:02}' if isinstance(x, int) else x)

In [140]:
df.groupby('dep').mean().sort_values('tx_incid', ascending=False)

pd.merge(df, df.groupby('dep').mean().sort_values('tx_incid', ascending=False).reset_index().head(5), on='dep', suffixes=('', '_mean')).sort_values('tx_incid', ascending=False)

,dep,date,reg,lib_dep,lib_reg,tx_pos,tx_incid,TO,R,hosp,...,dchosp_mean,reg_rea_mean,incid_hosp_mean,incid_rea_mean,incid_rad_mean,incid_dchosp_mean,reg_incid_rea_mean,pos_mean,pos_7j_mean,cv_dose1_mean
3906,69,2022-01-21,84,Rhône,Auvergne et Rhône-Alpes,34.00,4666.34,0.847943,NaN,922,...,3044.226667,214.990833,30.830692,5.768140,25.862385,3.975813,16.463720,1079.977213,7559.641543,76.8
3907,69,2022-01-22,84,Rhône,Auvergne et Rhône-Alpes,34.29,4654.19,0.851521,1.15,937,...,3044.226667,214.990833,30.830692,5.768140,25.862385,3.975813,16.463720,1079.977213,7559.641543,76.8
3905,69,2022-01-20,84,Rhône,Auvergne et Rhône-Alpes,33.29,4647.31,0.853309,NaN,912,...,3044.226667,214.990833,30.830692,5.768140,25.862385,3.975813,16.463720,1079.977213,7559.641543,76.8
3908,69,2022-01-23,84,Rhône,Auvergne et Rhône-Alpes,34.34,4631.54,0.835420,NaN,935,...,3044.226667,214.990833,30.830692,5.768140,25.862385,3.975813,16.463720,1079.977213,7559.641543,76.8
3904,69,2022-01-19,84,Rhône,Auvergne et Rhône-Alpes,32.44,4576.53,0.869410,NaN,866,...,3044.226667,214.990833,30.830692,5.768140,25.862385,3.975813,16.463720,1079.977213,7559.641543,76.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4486,972,2020-05-11,2,Martinique,Martinique,NaN,NaN,0.192308,NaN,19,...,554.883333,15.645833,5.237698,1.192661,4.035863,0.974145,1.192661,203.550394,1424.851008,43.0
4487,972,2020-05-12,2,Martinique,Martinique,NaN,NaN,0.192308,NaN,19,...,554.883333,15.645833,5.237698,1.192661,4.035863,0.974145,1.192661,203.550394,1424.851008,43.0
5629,972,2023-06-28,2,Martinique,Martinique,NaN,NaN,0.038462,NaN,14,...,554.883333,15.645833,5.237698,1.192661,4.035863,0.974145,1.192661,203.550394,1424.851008,43.0
5630,972,2023-06-29,2,Martinique,Martinique,NaN,NaN,0.038462,NaN,14,...,554.883333,15.645833,5.237698,1.192661,4.035863,0.974145,1.192661,203.550394,1424.851008,43.0
5631,972,2023-06-30,2,Martinique,Martinique,NaN,NaN,0.038462,NaN,14,...,554.883333,15.645833,5.237698,1.192661,4.035863,0.974145,1.192661,203.550394,1424.851008,43.0

In [141]:
pd.merge(df[['lib_dep', "dep"]].drop_duplicates().sort_values('lib_dep'), df.groupby('dep').mean().sort_values('tx_incid', ascending=False).reset_index(), on='dep', suffixes=('', '_mean')).sort_values('tx_incid', ascending=False)

,lib_dep,dep,reg,tx_pos,tx_incid,TO,R,hosp,rea,rad,dchosp,reg_rea,incid_hosp,incid_rea,incid_rad,incid_dchosp,reg_incid_rea,pos,pos_7j,cv_dose1
12,Bouches-du-Rhône,13,93.0,10.151998,427.600280,0.427136,1.031722,757.580000,117.053333,26589.715833,3846.875833,196.474167,47.735613,7.252711,41.760634,5.276897,13.434529,1246.573181,8725.346188,73.1
31,Finistère,29,53.0,18.259204,418.452075,0.256366,0.995847,156.514423,11.454327,4119.510817,531.221154,41.531250,10.043269,0.979567,8.980769,0.758413,3.418269,544.190591,3812.103739,84.9
82,Rhône,69,84.0,12.236626,401.326319,0.384608,1.044278,521.480000,79.000833,16798.513333,3044.226667,214.990833,30.830692,5.768140,25.862385,3.975813,16.463720,1079.977213,7559.641543,76.8
3,Alpes-Maritimes,6,93.0,11.271218,400.589150,0.427136,1.031722,312.742500,35.400000,7750.016667,1610.509167,196.474167,14.864053,2.834028,12.268557,2.237698,13.434529,620.699387,4344.765118,78.5
65,Martinique,972,2.0,10.773427,398.319220,0.601763,1.061131,80.201667,15.645833,2373.360833,554.883333,15.645833,5.237698,1.192661,4.035863,0.974145,1.192661,203.550394,1424.851008,43.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,Nièvre,58,27.0,13.617283,298.109790,0.377643,1.037833,53.170833,2.446667,1332.760833,301.574167,74.751667,2.902419,0.191827,2.449541,0.413678,5.637198,84.979842,594.837862,83.1
50,Indre,36,24.0,13.994049,295.741919,0.360468,1.036500,59.818333,2.998333,1326.125833,268.922500,64.887500,2.895746,0.222686,2.490409,0.373645,4.454545,91.479404,640.368975,83.0
36,Guyane,973,3.0,10.922656,207.286564,0.677179,1.005899,44.154167,8.803333,3892.699167,241.893333,8.803333,6.001668,0.720601,5.534612,0.346956,0.720601,86.198072,603.460123,34.1
67,Mayotte,976,6.0,6.414207,88.236126,0.467222,0.992683,15.713333,2.803333,1204.130000,115.268333,2.803333,1.851543,0.273561,1.547123,0.138449,0.273561,35.526731,248.324277,54.2
30,Finistère,29,53.0,2.315160,39.586378,0.245035,1.139032,57.519022,9.682065,318.972826,75.785326,39.695652,3.128065,0.594005,2.220708,0.583106,2.828338,52.246795,358.875000,NaN

In [142]:
df[['lib_dep', "dep"]].drop_duplicates()

                        lib_dep  dep
0                           Ain    1
1200                      Aisne    2
2400                     Allier    3
3600    Alpes-de-Haute-Provence    4
4800               Hautes-Alpes    5
...                         ...  ...
115200               Guadeloupe  971
116400               Martinique  972
117600                   Guyane  973
118800                  Réunion  974
120000                  Mayotte  976

[103 rows x 2 columns]

In [143]:
df.shape

(121200, 22)

In [144]:
import folium as fm

m = fm.Map(location=[46.603354, 1.888334], zoom_start=6)

# m.save('index.html')

In [9]:

import pandas as pd
deps = pd.read_csv('site\src\data\deps.csv')

In [6]:
df_mean = df.groupby('dep').mean().reset_index()
df_mean.dep = df_mean.dep.apply(lambda x: f'{x:02}' if isinstance(x, int) else x)

In [10]:
df_mean.to_csv('site\src\deps_mean.csv', index=False)

In [12]:
df_mean

,dep,reg,tx_pos,tx_incid,TO,R,hosp,rea,rad,dchosp,reg_rea,incid_hosp,incid_rea,incid_rad,incid_dchosp,reg_incid_rea,pos,pos_7j,cv_dose1
0,01,84.0,14.332252,365.808966,0.384608,1.044278,115.248333,7.218333,2923.804167,573.381667,214.990833,4.973311,0.617181,4.277731,0.728941,16.463720,344.292726,2410.246275,74.1
1,02,32.0,13.342997,317.666845,0.423725,1.030556,147.280000,15.250000,4753.400833,1058.428333,185.585000,9.146789,1.101751,7.686405,1.397832,13.162636,238.542507,1669.807187,80.1
2,03,84.0,12.726626,322.281315,0.384608,1.044278,74.062500,6.033333,2882.448333,572.640000,214.990833,6.406172,0.503753,5.488741,0.819850,16.463720,152.595968,1068.145486,82.6
3,04,93.0,12.244259,368.950911,0.427136,1.031722,66.538333,2.875833,1385.500833,243.352500,196.474167,2.946622,0.180150,2.315263,0.336113,13.434529,87.126205,609.863278,72.8
4,05,93.0,13.566862,358.745565,0.427136,1.031722,54.005000,4.535000,1574.055833,253.581667,196.474167,3.120934,0.371977,2.684737,0.346956,13.434529,72.537248,507.927257,78.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,971,1.0,10.989141,341.008554,0.427562,1.032952,83.483333,11.544167,2870.763333,641.107500,11.544167,5.804837,1.138449,4.706422,0.967473,1.138449,183.323401,1282.965819,40.8
97,972,2.0,10.773427,398.319220,0.601763,1.061131,80.201667,15.645833,2373.360833,554.883333,15.645833,5.237698,1.192661,4.035863,0.974145,1.192661,203.550394,1424.851008,43.0
98,973,3.0,10.922656,207.286564,0.677179,1.005899,44.154167,8.803333,3892.699167,241.893333,8.803333,6.001668,0.720601,5.534612,0.346956,0.720601,86.198072,603.460123,34.1
99,974,4.0,14.560938,376.410105,0.354936,1.035569,135.420833,18.456667,4083.235000,469.254167,18.456667,8.595496,1.504587,7.669725,0.841535,1.504587,463.193690,3242.112182,66.8
100,976,6.0,6.414207,88.236126,0.467222,0.992683,15.713333,2.803333,1204.130000,115.268333,2.803333,1.851543,0.273561,1.547123,0.138449,0.273561,35.526731,248.324277,54.2

In [11]:
df_mean.merge(deps, on='dep').to_csv('site/src/data/deps_mean.csv', index=False)

In [149]:
df = pd.merge(df, deps, on='dep')



# m.save('index.html')

ValueError: Location should consist of two numerical values, but '5.20.56' of type <class 'str'> is not convertible to float.

In [317]:
df_mean = df.groupby('dep').mean()

NameError: name 'df_mean' is not defined

In [324]:
df_mean.merge(deps, on='dep')

,dep,reg,tx_pos,tx_incid,TO,R,hosp,rea,rad,dchosp,...,incid_rea,incid_rad,incid_dchosp,reg_incid_rea,pos,pos_7j,cv_dose1,lib_dep,latt,long
0,01,84.0,14.332252,365.808966,0.384608,1.044278,115.248333,7.218333,2923.804167,573.381667,...,0.617181,4.277731,0.728941,16.463720,344.292726,2410.246275,74.1,Ain,46.099444,5.348889
1,02,32.0,13.342997,317.666845,0.423725,1.030556,147.280000,15.250000,4753.400833,1058.428333,...,1.101751,7.686405,1.397832,13.162636,238.542507,1669.807187,80.1,Aisne,49.559444,3.558333
2,03,84.0,12.726626,322.281315,0.384608,1.044278,74.062500,6.033333,2882.448333,572.640000,...,0.503753,5.488741,0.819850,16.463720,152.595968,1068.145486,82.6,Allier,46.393611,3.188333
3,04,93.0,12.244259,368.950911,0.427136,1.031722,66.538333,2.875833,1385.500833,243.352500,...,0.180150,2.315263,0.336113,13.434529,87.126205,609.863278,72.8,Alpes-de-Haute-Provence,44.106111,6.243889
4,05,93.0,13.566862,358.745565,0.427136,1.031722,54.005000,4.535000,1574.055833,253.581667,...,0.371977,2.684737,0.346956,13.434529,72.537248,507.927257,78.4,Hautes-Alpes,44.663611,6.263056
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,91,11.0,11.546705,344.366941,0.486078,1.018056,409.000000,51.480833,10558.676667,1833.282500,...,2.931610,15.637198,2.345288,33.280234,648.714286,4540.943909,75.2,Essonne,48.522222,2.243056
92,92,11.0,9.850158,367.032182,0.486078,1.018056,757.347500,91.669167,15587.086667,2618.212500,...,5.002502,21.606339,3.118432,33.280234,848.959684,5942.709904,77.9,Hauts-de-Seine,48.847222,2.245833
93,93,11.0,9.397905,310.890885,0.486078,1.018056,760.297500,68.488333,13719.050000,2352.976667,...,3.765638,18.125104,2.734779,33.280234,742.248904,5196.150745,67.0,Seine-Saint-Denis,48.917500,2.478056
94,94,11.0,10.384032,356.414365,0.486078,1.018056,608.777500,60.367500,14925.685833,2884.577500,...,4.444537,21.282736,3.502919,33.280234,718.482033,5029.174408,73.5,Val-de-Marne,48.777500,2.468889
95,95,11.0,11.201429,351.343365,0.486078,1.018056,372.595000,28.042500,10003.898333,1962.465000,...,1.792327,14.226856,2.407006,33.280234,628.852761,4402.348817,72.5,Val-d'Oise,49.082778,2.131111

In [373]:
m = fm.Map(location=[46.603354, 1.888334], zoom_start=6)

In [371]:
fm.GeoJson(
    data='departements.geojson',  # Chemin vers votre fichier GeoJSON
    style_function=lambda feature: {
        'color': 'red',  # Couleur des contours
        'fillColor': 'red',  # Couleur de remplissage
        'weight': 1,  # Épaisseur de la ligne
        'fillOpacity': 0.2,  # Opacité de remplissage
    }
).add_to(m)

In [385]:
from branca.colormap import linear

#Création d'une carte Folium centrée sur la France
m = fm.Map(location=[46.603354, 1.888334], zoom_start=6)

# Création d'une échelle de couleur en dégradé de rouge pour la pression hospitalière
# colormap = linear.Reds_09.scale(df_mean['hosp'].min(), df_mean['hosp'].max())
# colormap.caption = 'Hospitalisations'

# Ajout d'une couche choroplèthe pour représenter la pression hospitalière dans chaque département
fm.Choropleth(
    geo_data="departements.geojson",
    name='choropleth',
    data=df_mean,
    columns=['dep', 'hosp'],
    key_on='feature.properties.code',
    fill_color='YlOrRd',
    fill_opacity=0.7,
    line_opacity=0.2,
    legend_name='Hospitalisations',
    highlight=True
).add_to(m)

# Ajout de la légende de l'échelle de couleur
# colormap.add_to(m)

# Affichage de la carte
m.save('hospital_map.html')

In [381]:
df.columns

Index(['dep', 'date', 'reg', 'lib_dep', 'lib_reg', 'tx_pos', 'tx_incid', 'TO',
       'R', 'hosp', 'rea', 'rad', 'dchosp', 'reg_rea', 'incid_hosp',
       'incid_rea', 'incid_rad', 'incid_dchosp', 'reg_incid_rea', 'pos',
       'pos_7j', 'cv_dose1'],
      dtype='object')

In [370]:

m = fm.Map(location=[46.603354, 1.888334], zoom_start=6)
for a in df_mean.merge(deps, on='dep').iterrows():
    row = a[1]
    if row['dep'] == '64':
        print(row['latt'], row['long'])

    fm.Circle(
        location=[row['latt'], row['long']],

        radius=row['hosp'] * 50,
        color='crimson',
        fill=True,
        fill_color='crimson'
    ).add_to(m)

m.save('index.html')

43.25666666666667 0.7613888888888889

In [372]:
m.save('index.html')

In [362]:
df_mean.merge(deps, on='dep').tx_incid.max()

427.6002804557403

In [197]:
for a in groups.iterrows():
    row = a[1]
    fm.Marker([row['latt'], row['long']], popup=f'{row['dep']}: {row['tx_incid']}').add_to(m)

In [198]:
m.save('index.html')